// Build Ledgerline.exe - a real Windows executable, not a shortcut to a script.
//
// WHY THIS SHAPE. The three ways to get a .exe here were Electron (~150 MB on
// top of the Chromium this product already downloads), Tauri (a Rust toolchain
// in CI), and Node's own Single Executable Application. SEA wins on both counts
// that matter: the Node runtime is already bundled, so the exe costs nothing
// new to build, and there is no second toolchain to keep alive.
//
// Four steps, and the ORDER of the middle two is load-bearing:
//
//   1. compile a small CJS launcher into a SEA blob
//   2. copy the bundled node.exe and stamp the icon and version strings
//      (rcedit) - BEFORE the blob goes in, see below
//   3. inject the blob (postject)
//   4. flip the PE subsystem from CONSOLE to WINDOWS, so double-clicking it
//      opens the app and NOT a black terminal
//
// ⚠️ Stamping AFTER injection appears to work and does not. Measured
// 2026-08-28 on the same 92 MB binary: rcedit takes 0.3s on the plain
// node.exe and had still not finished after 35 minutes at 100% CPU on the
// postject output. (I first recorded that as antivirus interference. It is
// not - it is rcedit itself, and reordering makes it a third of a second.)
// The branding survives injection intact, so there is no reason to do it late.
//
// ⚠️ The launcher does not spawn anything. Node SEA requires a CommonJS entry,
// but a dynamic import() of an ESM file on disk works fine from inside one
// (measured 2026-08-28), so the exe loads src/ui/launch.mjs in-process. One
// process, one taskbar entry, and no `node.exe` visible anywhere.
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const STAGING = path.join(ROOT, "staging");
const BUILD = path.join(ROOT, "build", "exe");
const OUT = path.join(BUILD, "Ledgerline.exe");

const say = (m) => process.stdout.write(m + "\n");

/**
 * The launcher, as CommonJS, because that is what SEA accepts.
 *
 * It resolves the app relative to the executable, which is what makes the
 * installed layout work:  <install>\Ledgerline.exe  and  <install>\app\
 */
function launcherSource() {
  return `// Generated by scripts/build-exe.mjs - do not edit.
const path = require("node:path");
const fs = require("node:fs");
const { pathToFileURL } = require("node:url");

const here = path.dirname(process.execPath);
// Installed layout first, then a source checkout, so the same exe works when
// dropped next to the repo during development.
const candidates = [
  path.join(here, "app", "src", "ui", "launch.mjs"),
  path.join(here, "src", "ui", "launch.mjs"),
];
const entry = candidates.find((p) => fs.existsSync(p));

// There is no console attached to a GUI-subsystem process, so anything worth
// saying goes to a file the "Check Ledgerline health" shortcut can show.
const logDir = path.join(
  process.env.LOCALAPPDATA || require("node:os").homedir(),
  "Ledgerline",
  "logs",
);
function note(line) {
  try {
    fs.mkdirSync(logDir, { recursive: true });
    fs.appendFileSync(path.join(logDir, "launcher.log"), new Date().toISOString() + " " + line + "\\n");
  } catch {}
}

// A failure with no window and no console would be a silent no-op, which is
// the worst outcome available. Show it.
function fail(message) {
  note("FAILED: " + message);
  try {
    const { spawnSync } = require("node:child_process");
    spawnSync("mshta", [
      "javascript:alert(" + JSON.stringify("Ledgerline could not start.\\n\\n" + message + "\\n\\nLog: " + logDir) + ");close()",
    ], { windowsHide: true, timeout: 120000 });
  } catch {}
  process.exit(1);
}

if (!entry) fail("Could not find the application files next to " + process.execPath);

note("starting from " + entry);
import(pathToFileURL(entry).href)
  .then((m) => m.launchUI({ onProgress: note }))
  .then((r) => {
    if (r && r.ok === false) fail(r.reason || "the agent did not start");
    note("started");
  })
  .catch((e) => fail(e && e.stack ? e.stack.split("\\n").slice(0, 4).join("\\n") : String(e)));
`;
}

/** Flip the PE subsystem so Windows does not attach a console. */
function setGuiSubsystem(file) {
  const b = fs.readFileSync(file);
  const peOff = b.readUInt32LE(0x3c);
  if (b.toString("ascii", peOff, peOff + 4) !== "PE\0\0") throw new Error(`${file} is not a PE executable`);
  // 20-byte COFF header, then the optional header; Subsystem sits at +68 in
  // both PE32 and PE32+, so this needs no 32/64 branch.
  const off = peOff + 4 + 20 + 68;
  const before = b.readUInt16LE(off);
  if (before === 2) return { changed: false, before };
  b.writeUInt16LE(2, off); // IMAGE_SUBSYSTEM_WINDOWS_GUI
  fs.writeFileSync(file, b);
  return { changed: true, before };
}

function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { stdio: "pipe", encoding: "utf8", windowsHide: true, ...opts });
  return { ok: r.status === 0, status: r.status, out: (r.stdout ?? "") + (r.stderr ?? ""), error: r.error };
}

export async function buildExe({ version = "0.0.0" } = {}) {
  const nodeExe = path.join(STAGING, "node", "node.exe");
  if (!fs.existsSync(nodeExe)) {
    return { ok: false, reason: "staging/node/node.exe is missing - run build:installer first" };
  }

  fs.mkdirSync(BUILD, { recursive: true });
  const launcher = path.join(BUILD, "launcher.cjs");
  const seaConfig = path.join(BUILD, "sea-config.json");
  const blob = path.join(BUILD, "sea-prep.blob");
  fs.writeFileSync(launcher, launcherSource());
  fs.writeFileSync(
    seaConfig,
    JSON.stringify({ main: launcher, output: blob, disableExperimentalSEAWarning: true }, null, 2),
  );

  say("  Compiling the launcher...");
  const sea = run(process.execPath, ["--experimental-sea-config", seaConfig]);
  if (!sea.ok) return { ok: false, reason: `sea-config failed: ${sea.out.trim().split("\n").slice(-2).join(" ")}` };

  say("  Building the executable...");
  fs.copyFileSync(nodeExe, OUT);

  // Branding first - see the note at the top of this file.
  const icon = path.join(ROOT, "installer", "assets", "ledgerline.ico");
  let branded = false;
  const rcedit = path.join(ROOT, "node_modules", "rcedit", "bin", "rcedit-x64.exe");
  if (fs.existsSync(rcedit) && fs.existsSync(icon)) {
    say("  Stamping the icon and version...");
    const r = run(
      rcedit,
      [
        OUT,
        "--set-icon",
        icon,
        "--set-version-string",
        "ProductName",
        "Ledgerline",
        "--set-version-string",
        "FileDescription",
        "Ledgerline",
        "--set-version-string",
        "CompanyName",
        "Ledgerline contributors",
        "--set-file-version",
        version,
        "--set-product-version",
        version,
      ],
      { timeout: 120_000 },
    );
    branded = r.ok;
    // Still best effort: a missing icon is cosmetic, the shortcuts carry the
    // right one anyway, and failing the whole build over it would be wrong.
    if (!branded) say(`  (icon could not be stamped - continuing: ${r.out.trim().slice(-200)})`);
  }

  const postject = path.join(ROOT, "node_modules", "postject", "dist", "cli.js");
  if (!fs.existsSync(postject)) return { ok: false, reason: "postject is not installed (npm i -D postject)" };
  const inject = run(process.execPath, [
    postject,
    OUT,
    "NODE_SEA_BLOB",
    blob,
    "--sentinel-fuse",
    "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2",
  ]);
  if (!inject.ok) return { ok: false, reason: `injection failed: ${inject.out.trim().slice(-300)}` };

  // Last, because rcedit rewrites resources and can reset the header.
  const sub = setGuiSubsystem(OUT);
  say(`  Windowed: subsystem ${sub.before} -> 2`);

  // Prove it runs before calling it built.
  const check = run(OUT, ["--omni-selftest"], { timeout: 60_000 });
  const size = fs.statSync(OUT).size;
  return {
    ok: true,
    path: OUT,
    bytes: size,
    branded,
    subsystemChanged: sub.changed,
    ran: check.error === undefined,
  };
}

if (import.meta.url === pathToFileURLSafe(process.argv[1])) {
  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8"));
  const r = await buildExe({ version: pkg.version });
  if (!r.ok) {
    say(`FAILED: ${r.reason}`);
    process.exit(1);
  }
  say(`Built: ${r.path}  (${(r.bytes / 1e6).toFixed(1)} MB)`);
  say(`Icon stamped: ${r.branded ? "yes" : "no"}`);
}

function pathToFileURLSafe(p) {
  try {
    return new URL(`file://${path.resolve(p).replace(/\\/g, "/")}`).href;
  } catch {
    return "";
  }
}
